version: 2.1
jobs:
  install_dependencies:
    docker:
      - image: 'circleci/node:16.18.1'
    steps:
      - checkout
      - run: null
        name: install dependencies
        command: |
          npm install
  test_project:
    docker:
      - image: 'circleci/node:16.18.1'
    steps:
      - checkout
      - run: null
        name: test the project
        command: |
          npm test
workflows:
  default:
    jobs:
      - install_dependencies
      - test_project