version: 2.1
jobs:
  install_dependencies:
    docker:
      - image: 'cimg/node:16.18.1'
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            npm install
  test_project:
    docker:
      - image: 'cimg/node:16.18.1'
    steps:
      - checkout
      - run:
          name: test the project
          command: |
            npm test
workflows:
  default:
    jobs:
      - install_dependencies
      - test_project