version: 2.1
commands:
  install_nodejs:
    description: Install Nodejs
    steps:
      - run: null
        name: Install Node.js
        command: |
          curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
          sudo apt-get install -y nodejs
jobs:
  install_dependencies:
    docker:
      - image: 'circleci/node:16.18.1'
    steps:
      - checkout
      - run: null
        name: install dependencies
        command: |
          npm install
  test_project:
    docker:
      - image: 'circleci/node:16.18.1'
    steps:
      - checkout
      - run: null
        name: test the project
        command: |
          npm test

workflows:
  default:
    jobs:
      - install_dependencies
      - test_project