version: 2.1
jobs:
  install_dependencies:
    docker:
      - image: 'cimg/node:16.18.1'
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            npm install
            npm test
workflows:
  default:
    jobs:
      - install_dependencies